[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
    'npm install --frozen-lockfile',
]

[phases.build]
cmds = [
    'npm run build',
]
[start]
cmd = 'npm start'

[meta]
expose = '3000'
