[phases.setup]
nixPkgs = ['nodejs', 'bun']

[phases.install]
cmds = [
    'bun install --frozen-lockfile',
]

[phases.build]
cmds = [
    'bun run build',
]
[start]
cmd = 'bun start'

[meta]
expose = '3000'
