[phases.setup]
nixPkgs = ['nodejs', 'bun']

[phases.install]
cmds = [
    'bun install --frozen-lockfile --production',
]

[phases.build]
cmds = [
    'node node_modules/next/dist/bin/next build',
]

[start]
cmd = 'bun start'

[meta]
expose = '3000'
