[phases.setup]
nixPkgs = ['nodejs', 'bun']

[phases.install]
cmds = [
    'bun install --frozen-lockfile --production',
]

[phases.build]
cmds = [
    'ls -la src/components/ui',
    'ls -la src/components/about-page',
    'ls -la src/components/blogs',
    'ls -la src/components/common',
    'node node_modules/next/dist/bin/next build',
]
[start]
cmd = 'bun start'

[meta]
expose = '3000'
